#!/usr/bin/env python3
"""
gen_spec_summary.py — regenerate references/sources/openapi-specs/SPEC-SUMMARY.md

Produces a single flat, greppable catalog of EVERY operation and schema across both
embedded Akeneo specs:

  * saas-openapi.json     — SaaS/Serenity Web API      (OpenAPI 3.1.0)
  * classic-web-api.json  — classic CE/EE REST API     (Swagger 2.0)

Run after scripts/akeneo-pim/fetch_docs.sh. No third-party deps (stdlib json only).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SPECS = os.path.join(SKILL_ROOT, "references", "sources", "openapi-specs")
OUT = os.path.join(SPECS, "SPEC-SUMMARY.md")
METHODS = ("get", "post", "put", "patch", "delete", "head", "options")


def load(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def op_rows(spec):
    """Yield (tag, METHOD, path, summary) for every operation."""
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method.lower() not in METHODS or not isinstance(op, dict):
                continue
            tags = op.get("tags") or ["(untagged)"]
            summary = op.get("summary") or op.get("operationId") or ""
            yield tags[0], method.upper(), path, summary


def section(title, spec):
    if spec is None:
        return [f"## {title}\n\n_(spec file not present — run fetch_docs.sh)_\n"]
    info = spec.get("info", {})
    ver_key = "openapi" if "openapi" in spec else "swagger"
    lines = [f"## {title}\n"]
    lines.append(f"- **{ver_key}**: `{spec.get(ver_key)}`  ")
    lines.append(f"- **title**: {info.get('title')}  ")
    lines.append(f"- **info.version**: `{info.get('version')}`  ")
    # servers (3.x) or host+basePath (2.0)
    if spec.get("servers"):
        srv = ", ".join(s.get("url", "") for s in spec["servers"])
        lines.append(f"- **servers**: `{srv}`  ")
    elif spec.get("host") or spec.get("basePath"):
        lines.append(f"- **host/basePath**: `{spec.get('host','')}{spec.get('basePath','')}`  ")
    rows = sorted(op_rows(spec), key=lambda r: (r[0].lower(), r[2], r[1]))
    schemas = spec.get("components", {}).get("schemas") if "components" in spec else spec.get("definitions")
    schemas = schemas or {}
    lines.append(f"- **operations**: {len(rows)}  |  **paths**: {len(spec.get('paths') or {})}  "
                 f"|  **schemas**: {len(schemas)}\n")
    # group by tag
    cur = None
    for tag, method, path, summary in rows:
        if tag != cur:
            cur = tag
            lines.append(f"\n### {tag}\n")
        sfx = f" — {summary}" if summary else ""
        lines.append(f"- `{method:6} {path}`{sfx}")
    # schema index
    if schemas:
        lines.append(f"\n### Schemas ({len(schemas)})\n")
        lines.append(", ".join(f"`{n}`" for n in sorted(schemas)))
    lines.append("")
    return lines


def main():
    saas = load(os.path.join(SPECS, "saas-openapi.json"))
    classic = load(os.path.join(SPECS, "classic-web-api.json"))
    out = [
        "# Akeneo API — Flat Spec Catalog",
        "",
        "> Auto-generated by `scripts/akeneo-pim/gen_spec_summary.py`. Do not edit by hand.",
        "> Flat, greppable index of every operation + schema across both embedded specs.",
        "> The specs themselves are the source of truth; this is a finding aid.",
        "",
        "| Spec | File | Standard | Surface |",
        "| --- | --- | --- | --- |",
        "| SaaS / Serenity | `saas-openapi.json` | OpenAPI 3.1.0 | modern (UUID products, Catalogs, Workflows, Apps) |",
        "| Classic CE/EE | `classic-web-api.json` | Swagger 2.0 | on-prem / PaaS REST |",
        "",
    ]
    out += section("SaaS / Serenity Web API (`saas-openapi.json`)", saas)
    out += ["\n---\n"]
    out += section("Classic CE/EE REST API (`classic-web-api.json`)", classic)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    n_saas = len(list(op_rows(saas))) if saas else 0
    n_classic = len(list(op_rows(classic))) if classic else 0
    print(f"wrote {OUT}")
    print(f"  SaaS ops: {n_saas}   Classic ops: {n_classic}")


if __name__ == "__main__":
    sys.exit(main())
